[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cookie = "cookieAAc8qiHmnJLuhHokCLLccipBYnKRzyFCMgcFE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/cookie.ts"

[test.validator]
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "programs/mpl_token_metadata.so"